server:
  port: 7777

spring:
  datasource:
    url: jdbc:postgresql://159.223.205.182:5432/barkibu_bd
    username: postgres
    password: XSUc$DP)gPah()UI
    driver-class-name: org.postgresql.Driver

