### Test Auth
### Dos Opciones
### Path Variable: http://localhost:7777/v1/api/auth/{user_id}
### Query Param: http://localhost:7777/v1/api/auth?user_id={user_id} Esto se utilzia para paginacion


### USUARIO ADMIN
POST http://localhost:7777/v1/api/auth
Content-Type: application/json
Accept: application/json

{
 "userName":"apanique",
 "password": "1234567"
}

### USUARIO VETERINARIO
POST http://localhost:7777/v1/api/auth
Content-Type: application/json
Accept: application/json

{
 "userName":"czarate",
 "password": "12345"
}

### USUARIO DUEÑO DE MASCOTA
POST http://localhost:7777/v1/api/auth
Content-Type: application/json
Accept: application/json

{
 "userName":"jose1234",
 "password": "123456"
}

### veterinario
POST http://localhost:7777/v1/api/auth
Content-Type: application/json
Accept: application/json

{
  "userName":"juan1234",
  "password": "123456"
}

### Refresh Token

POST http://localhost:7777/v1/api/auth/refresh-token
Content-Type: application/json
Accept: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGFuaXF1ZSIsImlzcyI6InVjYiIsInJlZnJlc2giOnRydWUsImV4cCI6MTY2ODkwMTY0NywiaWF0IjoxNjY4OTAxNTI3fQ.m1Jndrh857q6tWhLWEnej9bbQ8VxZu9_E-7QrCff0xk
