### Test Auth
### Dos Opciones
### Path Variable: http://localhost:7777/v1/api/auth/{user_id}
### Query Param: http://localhost:7777/v1/api/auth?user_id={user_id} Esto se utilzia para paginacion


### USUARIO ADMIN
POST http://localhost:7777/v1/api/auth
Content-Type: application/json
Accept: application/json

{
 "userName":"apanique", 
 "password": "1234567"
}

### USUARIO VETERINARIO
POST http://localhost:7777/v1/api/auth
Content-Type: application/json
Accept: application/json

{
 "userName":"juan123", 
 "password": "123456"
}

### USUARIO DUEÑO DE MASCOTA
POST http://localhost:7777/v1/api/auth
Content-Type: application/json
Accept: application/json

{
 "userName":"jose123", 
 "password": "123456"
}