
### Add new Pet Owner User
POST http://localhost:7777/v1/api/pet
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3NlMTIzNCIsInJvbGVzIjpbIlJFR0lTVFJBUiBNQVNDT1RBIiwiUkVHSVNUUkFSIFRSQVRBTUlFTlRPUyBERSBMQSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIERVRcORTyBERSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIExBIE1BU0NPVEEiLCJFRElUQVIgVFJBVEFNSUVOVE9TIERFIExBIE1BU0NPVEEiLCJQVUJMSUNBUiBQUkVHVU5UQSJdLCJpc3MiOiJ1Y2IiLCJyZWZyZXNoIjpmYWxzZSwiZXhwIjoxNjcxNDg3MjkwLCJpYXQiOjE2Njg0ODcyOTB9.3nXm-cGQT8hiDT0LUim0LXB1zrbO84iT4I2BiZepZ1Y

{
    "breedId": "1",
    "name": "Bella",
    "gender": "hembra",
    "castrated": "true",
    "bornDate": "2018-01-01",
    "photoPath": "https://imageio.forbes.com/specials-images/dam/imageserve/1068867780/960x0.jpg?format=jpg&width=960",
    "chipNumber": "123456789"
}


###Info pets by token
http://localhost:7777/v1/api/pet/pet-info/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGFuaXF1ZSIsInJvbGVzIjpbIlJFR0lTVFJBUiBVU1VBUklPIFZFVEVSSU5BUklPIiwiUkVHSVNUUkFSIE1BU0NPVEEiLCJSRUdJU1RSQVIgVFJBVEFNSUVOVE9TIERFIExBIE1BU0NPVEEiLCJFRElUQVIgSU5GT1JNQUNJT04gREUgRFVFw5FPIERFIE1BU0NPVEEiLCJFRElUQVIgSU5GT1JNQUNJT04gREUgTEEgTUFTQ09UQSIsIkVESVRBUiBUUkFUQU1JRU5UT1MgREUgTEEgTUFTQ09UQSIsIlBVQkxJQ0FSIFBSRUdVTlRBIiwiRURJVEFSIElORk9STUFDSU9OIERFIFZFVEVSSU5BUklPIiwiRURJVEFSIElORk9STUFDSU9OIERFIENMSU5JQ0EgVkVURVJJTkFSSUEiLCJQVUJMSUNBUiBSRVNQVUVTVEEiXSwiaXNzIjoidWNiIiwicmVmcmVzaCI6ZmFsc2UsImV4cCI6MTY3MTI4NzQ4MCwiaWF0IjoxNjY4Mjg3NDgwfQ.SuKI_MQ2NjrYIqwCYQyIFmziKSzeNkTSDBILRPGjHG8

###Info pet by id
GET  http://localhost:7777/v1/api/pet/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjemFyYXRlIiwicm9sZXMiOlsiRURJVEFSIElORk9STUFDSU9OIERFIFZFVEVSSU5BUklPIiwiRURJVEFSIElORk9STUFDSU9OIERFIENMSU5JQ0EgVkVURVJJTkFSSUEiLCJQVUJMSUNBUiBSRVNQVUVTVEEiLCJFRElUQVIgUkVTUFVFU1RBIl0sImlzcyI6InVjYiIsInJlZnJlc2giOmZhbHNlLCJleHAiOjE2NzE0ODg1ODEsImlhdCI6MTY2ODQ4ODU4MX0.kIIOzz_O4Noczn0O3Z9vfxlKmBUljE8Z2Pn3RtjO9qg
{
    "name": "Charil",
    "gender": "Macho",
    "castrated": "True",
    "bornDate": "2021-12-10T04:00:00.000+00:00",
    "breedId": "2",
    "chipNumber": "9075956746"

}

