
### Add new Pet Owner User
POST http://localhost:7777/v1/api/pet
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3NlMTIzNCIsInJvbGVzIjpbIlJFR0lTVFJBUiBNQVNDT1RBIiwiUkVHSVNUUkFSIFRSQVRBTUlFTlRPUyBERSBMQSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIERVRcORTyBERSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIExBIE1BU0NPVEEiLCJFRElUQVIgVFJBVEFNSUVOVE9TIERFIExBIE1BU0NPVEEiLCJQVUJMSUNBUiBQUkVHVU5UQSJdLCJpc3MiOiJ1Y2IiLCJyZWZyZXNoIjpmYWxzZSwiZXhwIjoxNjcxNDg3MjkwLCJpYXQiOjE2Njg0ODcyOTB9.3nXm-cGQT8hiDT0LUim0LXB1zrbO84iT4I2BiZepZ1Y

{
    "breedId": "1",
    "name": "Bella",
    "gender": "hembra",
    "castrated": "true",
    "bornDate": "2018-01-01",
    "photoPath": "https://imageio.forbes.com/specials-images/dam/imageserve/1068867780/960x0.jpg?format=jpg&width=960",
    "chipNumber": "123456789"
}
