### Add new Question
POST http://localhost:7777/v1/api/new-question
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3NlMTIzNCIsInJvbGVzIjpbIlJFR0lTVFJBUiBNQVNDT1RBIiwiUkVHSVNUUkFSIFRSQVRBTUlFTlRPUyBERSBMQSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIERVRcORTyBERSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIExBIE1BU0NPVEEiLCJFRElUQVIgVFJBVEFNSUVOVE9TIERFIExBIE1BU0NPVEEiLCJQVUJMSUNBUiBQUkVHVU5UQSJdLCJpc3MiOiJ1Y2IiLCJyZWZyZXNoIjpmYWxzZSwiZXhwIjoxNjcxNDg3MjkwLCJpYXQiOjE2Njg0ODcyOTB9.3nXm-cGQT8hiDT0LUim0LXB1zrbO84iT4I2BiZepZ1Y

{
  "categoryId": "1",
  "petId": "1",
  "problem": "Mi perro se comio un hueso",
  "detailedDescription": "Mi perro vomita y no puede expulsar el hueso",
  "answered": "false",
  "questionDate": "2022-04-05"
}

###
POST http://localhost:7777/v1/api/new-question
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGFuaXF1ZSIsInJvbGVzIjpbIlJFR0lTVFJBUiBVU1VBUklPIFZFVEVSSU5BUklPIiwiUkVHSVNUUkFSIE1BU0NPVEEiLCJSRUdJU1RSQVIgVFJBVEFNSUVOVE9TIERFIExBIE1BU0NPVEEiLCJFRElUQVIgSU5GT1JNQUNJT04gREUgRFVFw5FPIERFIE1BU0NPVEEiLCJFRElUQVIgSU5GT1JNQUNJT04gREUgTEEgTUFTQ09UQSIsIkVESVRBUiBUUkFUQU1JRU5UT1MgREUgTEEgTUFTQ09UQSIsIlBVQkxJQ0FSIFBSRUdVTlRBIiwiRURJVEFSIElORk9STUFDSU9OIERFIFZFVEVSSU5BUklPIiwiRURJVEFSIElORk9STUFDSU9OIERFIENMSU5JQ0EgVkVURVJJTkFSSUEiLCJQVUJMSUNBUiBSRVNQVUVTVEEiXSwiaXNzIjoidWNiIiwicmVmcmVzaCI6ZmFsc2UsImV4cCI6MTY3MTI4NzQ4MCwiaWF0IjoxNjY4Mjg3NDgwfQ.SuKI_MQ2NjrYIqwCYQyIFmziKSzeNkTSDBILRPGjHG8

{
  "categoryId": "1",
  "petId": "1",
  "problem": "Mi perro se comio un hueso",
  "detailedDescription": "Mi perro vomita y no puede expulsar el hueso",
  "answered": "false",
  "questionDate": "2022-04-05"
}
