GET http://localhost:7777/v1/api/user/owner/question/czarate
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjemFyYXRlIiwicm9sZXMiOlsiRURJVEFSIElORk9STUFDSU9OIERFIFZFVEVSSU5BUklPIiwiRURJVEFSIElORk9STUFDSU9OIERFIENMSU5JQ0EgVkVURVJJTkFSSUEiLCJQVUJMSUNBUiBSRVNQVUVTVEEiXSwiaXNzIjoidWNiIiwicmVmcmVzaCI6ZmFsc2UsImV4cCI6MTY3MTMxNDYwMSwiaWF0IjoxNjY4MzE0NjAxfQ.hffFmxApO-4sn5lVa3zuguAamWtFEuqxrDhAFBexgw8
