### Request Password Recovery Code
POST http://localhost:7777/v1/api/recovery-account
Content-Type: application/json
Accept: application/json

{
    "email": "chrisalanapazaa@gmail.com"
}
### Request Password Change
POST http://localhost:7777/v1/api/recovery-account/hash-code
Content-Type: application/json
Accept: application/json

{
  "email": "chrisalanapazaa@gmail.com",
  "hashCode": "605479"
}
### Request Password Update
POST http://localhost:7777/v1/api/recovery-account/password
Content-Type: application/json
Accept: application/json

{
  "email": "chrisalanapazaa@gmail.com",
  "hashCode": "789952",
  "password": "pokemon",
  "confirmPassword": "pokemon"
}



