### Add new user Test
POST http://localhost:7777/v1/api/user/veterinarian
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGFuaXF1ZSIsInJvbGVzIjpbIkNSRUFSIENPTlNVTFRBIiwiTEVFUiBDT05TVUxUQSIsIkNSRUFSIFVTVUFSSU8iXSwiaXNzIjoidWNiIiwicmVmcmVzaCI6ZmFsc2UsImV4cCI6MTY2ODA0Nzk5OSwiaWF0IjoxNjY4MDQ3Njk5fQ.q9qcuQjwa5jtZZmJx3sUfsRm2IRA5vycseB5R1msWdU

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "jd2@ucb.edu.bo",
    "userName": "johndoe2",
    "password": "123456",
    "confirmPassword": "123456"
}

### Add new Pet Owner User
POST http://localhost:7777/v1/api/user/pet-owner
Content-Type: application/json
Accept: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "jd5@ucb.edu.bo",
    "userName": "johndoe5",
    "password": "123456"
}

### Get user veterinarian info by token
GET http://localhost:7777/v1/api/user/veterinarian
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGFuaXF1ZSIsInJvbGVzIjpbIlJFR0lTVFJBUiBVU1VBUklPIFZFVEVSSU5BUklPIiwiUkVHSVNUUkFSIE1BU0NPVEEiLCJSRUdJU1RSQVIgVFJBVEFNSUVOVE9TIERFIExBIE1BU0NPVEEiLCJFRElUQVIgSU5GT1JNQUNJT04gREUgRFVFw5FPIERFIE1BU0NPVEEiLCJFRElUQVIgSU5GT1JNQUNJT04gREUgTEEgTUFTQ09UQSIsIkVESVRBUiBUUkFUQU1JRU5UT1MgREUgTEEgTUFTQ09UQSIsIlBVQkxJQ0FSIFBSRUdVTlRBIiwiRURJVEFSIElORk9STUFDSU9OIERFIFZFVEVSSU5BUklPIiwiRURJVEFSIElORk9STUFDSU9OIERFIENMSU5JQ0EgVkVURVJJTkFSSUEiLCJQVUJMSUNBUiBSRVNQVUVTVEEiXSwiaXNzIjoidWNiIiwicmVmcmVzaCI6ZmFsc2UsImV4cCI6MTY3MTI5MjExMiwiaWF0IjoxNjY4MjkyMTEyfQ.1dZQWL0siAy-yJ4AFns1aKzG6tkLgaHxUBSIKB9IcDA
