### Add new Pet Owner User
POST http://localhost:7777/v1/api/user/pet-owner
Content-Type: application/json
Accept: application/json

{
  "firstName": "Jose",
  "lastName": "Alvarado",
  "email": "josae_alvarado@ucb.edu.bo",
  "userName": "jose12345",
  "password": "123456",
  "confirmPassword": "123456"
}