
### Get user veterinarian info by token
GET http://localhost:7777/v1/api/veterinarian/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqdWFuMTIzNCIsInJvbGVzIjpbIkVESVRBUiBJTkZPUk1BQ0lPTiBERSBWRVRFUklOQVJJTyIsIkVESVRBUiBJTkZPUk1BQ0lPTiBERSBDTElOSUNBIFZFVEVSSU5BUklBIiwiUFVCTElDQVIgUkVTUFVFU1RBIiwiRURJVEFSIFJFU1BVRVNUQSJdLCJpc3MiOiJ1Y2IiLCJyZWZyZXNoIjpmYWxzZSwiZXhwIjoxNjcxODk3NTIyLCJpYXQiOjE2Njg4OTc1MjJ9.V99Ml2juUR-1PSwpYSVLPesV45nZbsi_IuvPF7bu3WQ

### Get user veterinarian info by username
GET http://localhost:7777/v1/api/veterinarian/czarate
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3NlMTIzNCIsInJvbGVzIjpbIlJFR0lTVFJBUiBNQVNDT1RBIiwiUkVHSVNUUkFSIFRSQVRBTUlFTlRPUyBERSBMQSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIERVRcORTyBERSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIExBIE1BU0NPVEEiLCJFRElUQVIgVFJBVEFNSUVOVE9TIERFIExBIE1BU0NPVEEiLCJQVUJMSUNBUiBQUkVHVU5UQSJdLCJpc3MiOiJ1Y2IiLCJyZWZyZXNoIjpmYWxzZSwiZXhwIjoxNjcxNDg3NjQ4LCJpYXQiOjE2Njg0ODc2NDh9.ogfX8EtIlHACDTip3oEGW0eiYPKXcz8FMQ3f3SnhJBA

### Get veterinarian ranking by token
GET http://localhost:7777/v1/api/veterinarian/ranking
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGFuaXF1ZSIsInJvbGVzIjpbIlJFR0lTVFJBUiBVU1VBUklPIFZFVEVSSU5BUklPIiwiUkVHSVNUUkFSIE1BU0NPVEEiLCJSRUdJU1RSQVIgVFJBVEFNSUVOVE9TIERFIExBIE1BU0NPVEEiLCJFRElUQVIgSU5GT1JNQUNJT04gREUgRFVFw5FPIERFIE1BU0NPVEEiLCJFRElUQVIgSU5GT1JNQUNJT04gREUgTEEgTUFTQ09UQSIsIkVESVRBUiBUUkFUQU1JRU5UT1MgREUgTEEgTUFTQ09UQSIsIlBVQkxJQ0FSIFBSRUdVTlRBIiwiRURJVEFSIElORk9STUFDSU9OIERFIFZFVEVSSU5BUklPIiwiRURJVEFSIElORk9STUFDSU9OIERFIENMSU5JQ0EgVkVURVJJTkFSSUEiLCJQVUJMSUNBUiBSRVNQVUVTVEEiLCJFRElUQVIgUkVTUFVFU1RBIl0sImlzcyI6InVjYiIsInJlZnJlc2giOmZhbHNlLCJleHAiOjE2NzE4OTU3NjIsImlhdCI6MTY2ODg5NTc2Mn0.Sqf7pZ7CFk5axF873Z84IMBqbvcoU9K7dv0_a23Ltc8

### Get veterinarian ranking by username
GET http://localhost:7777/v1/api/veterinarian/ranking/czarate
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3NlMTIzNCIsInJvbGVzIjpbIlJFR0lTVFJBUiBNQVNDT1RBIiwiUkVHSVNUUkFSIFRSQVRBTUlFTlRPUyBERSBMQSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIERVRcORTyBERSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIExBIE1BU0NPVEEiLCJFRElUQVIgVFJBVEFNSUVOVE9TIERFIExBIE1BU0NPVEEiLCJQVUJMSUNBUiBQUkVHVU5UQSJdLCJpc3MiOiJ1Y2IiLCJyZWZyZXNoIjpmYWxzZSwiZXhwIjoxNjcxNDg3NjQ4LCJpYXQiOjE2Njg0ODc2NDh9.ogfX8EtIlHACDTip3oEGW0eiYPKXcz8FMQ3f3SnhJBA

### Get veterinarian reputation by token
GET http://localhost:7777/v1/api/veterinarian/reputation
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGFuaXF1ZSIsInJvbGVzIjpbIlJFR0lTVFJBUiBVU1VBUklPIFZFVEVSSU5BUklPIiwiUkVHSVNUUkFSIE1BU0NPVEEiLCJSRUdJU1RSQVIgVFJBVEFNSUVOVE9TIERFIExBIE1BU0NPVEEiLCJFRElUQVIgSU5GT1JNQUNJT04gREUgRFVFw5FPIERFIE1BU0NPVEEiLCJFRElUQVIgSU5GT1JNQUNJT04gREUgTEEgTUFTQ09UQSIsIkVESVRBUiBUUkFUQU1JRU5UT1MgREUgTEEgTUFTQ09UQSIsIlBVQkxJQ0FSIFBSRUdVTlRBIiwiRURJVEFSIElORk9STUFDSU9OIERFIFZFVEVSSU5BUklPIiwiRURJVEFSIElORk9STUFDSU9OIERFIENMSU5JQ0EgVkVURVJJTkFSSUEiLCJQVUJMSUNBUiBSRVNQVUVTVEEiLCJFRElUQVIgUkVTUFVFU1RBIl0sImlzcyI6InVjYiIsInJlZnJlc2giOmZhbHNlLCJleHAiOjE2NzE4OTU3NjIsImlhdCI6MTY2ODg5NTc2Mn0.Sqf7pZ7CFk5axF873Z84IMBqbvcoU9K7dv0_a23Ltc8

### Get veterinarian reputation by username
GET http://localhost:7777/v1/api/veterinarian/reputation/czarate
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3NlMTIzNCIsInJvbGVzIjpbIlJFR0lTVFJBUiBNQVNDT1RBIiwiUkVHSVNUUkFSIFRSQVRBTUlFTlRPUyBERSBMQSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIERVRcORTyBERSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIExBIE1BU0NPVEEiLCJFRElUQVIgVFJBVEFNSUVOVE9TIERFIExBIE1BU0NPVEEiLCJQVUJMSUNBUiBQUkVHVU5UQSJdLCJpc3MiOiJ1Y2IiLCJyZWZyZXNoIjpmYWxzZSwiZXhwIjoxNjcxNDg3NjQ4LCJpYXQiOjE2Njg0ODc2NDh9.ogfX8EtIlHACDTip3oEGW0eiYPKXcz8FMQ3f3SnhJBA

### Get veterinarian contributions by token
GET http://localhost:7777/v1/api/veterinarian/contribution
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGFuaXF1ZSIsInJvbGVzIjpbIlJFR0lTVFJBUiBVU1VBUklPIFZFVEVSSU5BUklPIiwiUkVHSVNUUkFSIE1BU0NPVEEiLCJSRUdJU1RSQVIgVFJBVEFNSUVOVE9TIERFIExBIE1BU0NPVEEiLCJFRElUQVIgSU5GT1JNQUNJT04gREUgRFVFw5FPIERFIE1BU0NPVEEiLCJFRElUQVIgSU5GT1JNQUNJT04gREUgTEEgTUFTQ09UQSIsIkVESVRBUiBUUkFUQU1JRU5UT1MgREUgTEEgTUFTQ09UQSIsIlBVQkxJQ0FSIFBSRUdVTlRBIiwiRURJVEFSIElORk9STUFDSU9OIERFIFZFVEVSSU5BUklPIiwiRURJVEFSIElORk9STUFDSU9OIERFIENMSU5JQ0EgVkVURVJJTkFSSUEiLCJQVUJMSUNBUiBSRVNQVUVTVEEiLCJFRElUQVIgUkVTUFVFU1RBIl0sImlzcyI6InVjYiIsInJlZnJlc2giOmZhbHNlLCJleHAiOjE2NzE4OTU3NjIsImlhdCI6MTY2ODg5NTc2Mn0.Sqf7pZ7CFk5axF873Z84IMBqbvcoU9K7dv0_a23Ltc8

### Get veterinarian contributions by username
GET http://localhost:7777/v1/api/veterinarian/contribution/gsallinger14
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3NlMTIzNCIsInJvbGVzIjpbIlJFR0lTVFJBUiBNQVNDT1RBIiwiUkVHSVNUUkFSIFRSQVRBTUlFTlRPUyBERSBMQSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIERVRcORTyBERSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIExBIE1BU0NPVEEiLCJFRElUQVIgVFJBVEFNSUVOVE9TIERFIExBIE1BU0NPVEEiLCJQVUJMSUNBUiBQUkVHVU5UQSJdLCJpc3MiOiJ1Y2IiLCJyZWZyZXNoIjpmYWxzZSwiZXhwIjoxNjcxNDg3NjQ4LCJpYXQiOjE2Njg0ODc2NDh9.ogfX8EtIlHACDTip3oEGW0eiYPKXcz8FMQ3f3SnhJBA

### Get veterinarian's answers by token
GET http://localhost:7777/v1/api/veterinarian/answers
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqdWFuMTIzIiwicm9sZXMiOlsiRURJVEFSIElORk9STUFDSU9OIERFIFZFVEVSSU5BUklPIiwiRURJVEFSIElORk9STUFDSU9OIERFIENMSU5JQ0EgVkVURVJJTkFSSUEiLCJQVUJMSUNBUiBSRVNQVUVTVEEiLCJFRElUQVIgUkVTUFVFU1RBIl0sImlzcyI6InVjYiIsInJlZnJlc2giOmZhbHNlLCJleHAiOjE2NzE0ODgwNzUsImlhdCI6MTY2ODQ4ODA3NX0.b3Ob-b8Rw6zORCuN24yxt4HCCyHrXZAdgCuRuYCEvmE

