
### Get user veterinarian info by token
GET http://localhost:7777/v1/api/veterinarian/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjemFyYXRlIiwicm9sZXMiOlsiRURJVEFSIElORk9STUFDSU9OIERFIFZFVEVSSU5BUklPIiwiRURJVEFSIElORk9STUFDSU9OIERFIENMSU5JQ0EgVkVURVJJTkFSSUEiLCJQVUJMSUNBUiBSRVNQVUVTVEEiLCJFRElUQVIgUkVTUFVFU1RBIl0sImlzcyI6InVjYiIsInJlZnJlc2giOmZhbHNlLCJleHAiOjE2NzE0ODc3NzcsImlhdCI6MTY2ODQ4Nzc3N30.W6ZEjNsmfebZyuNwCCtjFeDi3tqe8qiX6zKDQU7VMMg

### Get user veterinarian info by username
GET http://localhost:7777/v1/api/veterinarian/czarate
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3NlMTIzNCIsInJvbGVzIjpbIlJFR0lTVFJBUiBNQVNDT1RBIiwiUkVHSVNUUkFSIFRSQVRBTUlFTlRPUyBERSBMQSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIERVRcORTyBERSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIExBIE1BU0NPVEEiLCJFRElUQVIgVFJBVEFNSUVOVE9TIERFIExBIE1BU0NPVEEiLCJQVUJMSUNBUiBQUkVHVU5UQSJdLCJpc3MiOiJ1Y2IiLCJyZWZyZXNoIjpmYWxzZSwiZXhwIjoxNjcxNDg3NjQ4LCJpYXQiOjE2Njg0ODc2NDh9.ogfX8EtIlHACDTip3oEGW0eiYPKXcz8FMQ3f3SnhJBA

### Get veterinarian ranking by token
GET http://localhost:7777/v1/api/veterinarian/ranking
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjemFyYXRlIiwicm9sZXMiOlsiRURJVEFSIElORk9STUFDSU9OIERFIFZFVEVSSU5BUklPIiwiRURJVEFSIElORk9STUFDSU9OIERFIENMSU5JQ0EgVkVURVJJTkFSSUEiLCJQVUJMSUNBUiBSRVNQVUVTVEEiLCJFRElUQVIgUkVTUFVFU1RBIl0sImlzcyI6InVjYiIsInJlZnJlc2giOmZhbHNlLCJleHAiOjE2NzE0ODc3NzcsImlhdCI6MTY2ODQ4Nzc3N30.W6ZEjNsmfebZyuNwCCtjFeDi3tqe8qiX6zKDQU7VMMg

### Get veterinarian ranking by username
GET http://localhost:7777/v1/api/veterinarian/ranking/czarate
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3NlMTIzNCIsInJvbGVzIjpbIlJFR0lTVFJBUiBNQVNDT1RBIiwiUkVHSVNUUkFSIFRSQVRBTUlFTlRPUyBERSBMQSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIERVRcORTyBERSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIExBIE1BU0NPVEEiLCJFRElUQVIgVFJBVEFNSUVOVE9TIERFIExBIE1BU0NPVEEiLCJQVUJMSUNBUiBQUkVHVU5UQSJdLCJpc3MiOiJ1Y2IiLCJyZWZyZXNoIjpmYWxzZSwiZXhwIjoxNjcxNDg3NjQ4LCJpYXQiOjE2Njg0ODc2NDh9.ogfX8EtIlHACDTip3oEGW0eiYPKXcz8FMQ3f3SnhJBA

### Get veterinarian reputation by token
GET http://localhost:7777/v1/api/veterinarian/reputation
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjemFyYXRlIiwicm9sZXMiOlsiRURJVEFSIElORk9STUFDSU9OIERFIFZFVEVSSU5BUklPIiwiRURJVEFSIElORk9STUFDSU9OIERFIENMSU5JQ0EgVkVURVJJTkFSSUEiLCJQVUJMSUNBUiBSRVNQVUVTVEEiLCJFRElUQVIgUkVTUFVFU1RBIl0sImlzcyI6InVjYiIsInJlZnJlc2giOmZhbHNlLCJleHAiOjE2NzE0ODc3NzcsImlhdCI6MTY2ODQ4Nzc3N30.W6ZEjNsmfebZyuNwCCtjFeDi3tqe8qiX6zKDQU7VMMg

### Get veterinarian reputation by username
GET http://localhost:7777/v1/api/veterinarian/reputation/czarate
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3NlMTIzNCIsInJvbGVzIjpbIlJFR0lTVFJBUiBNQVNDT1RBIiwiUkVHSVNUUkFSIFRSQVRBTUlFTlRPUyBERSBMQSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIERVRcORTyBERSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIExBIE1BU0NPVEEiLCJFRElUQVIgVFJBVEFNSUVOVE9TIERFIExBIE1BU0NPVEEiLCJQVUJMSUNBUiBQUkVHVU5UQSJdLCJpc3MiOiJ1Y2IiLCJyZWZyZXNoIjpmYWxzZSwiZXhwIjoxNjcxNDg3NjQ4LCJpYXQiOjE2Njg0ODc2NDh9.ogfX8EtIlHACDTip3oEGW0eiYPKXcz8FMQ3f3SnhJBA

### Get veterinarian contributions by token
GET http://localhost:7777/v1/api/veterinarian/contribution
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjemFyYXRlIiwicm9sZXMiOlsiRURJVEFSIElORk9STUFDSU9OIERFIFZFVEVSSU5BUklPIiwiRURJVEFSIElORk9STUFDSU9OIERFIENMSU5JQ0EgVkVURVJJTkFSSUEiLCJQVUJMSUNBUiBSRVNQVUVTVEEiLCJFRElUQVIgUkVTUFVFU1RBIl0sImlzcyI6InVjYiIsInJlZnJlc2giOmZhbHNlLCJleHAiOjE2NzE0ODc3NzcsImlhdCI6MTY2ODQ4Nzc3N30.W6ZEjNsmfebZyuNwCCtjFeDi3tqe8qiX6zKDQU7VMMg

### Get veterinarian contributions by username
GET http://localhost:7777/v1/api/veterinarian/contribution/gsallinger14
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb3NlMTIzNCIsInJvbGVzIjpbIlJFR0lTVFJBUiBNQVNDT1RBIiwiUkVHSVNUUkFSIFRSQVRBTUlFTlRPUyBERSBMQSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIERVRcORTyBERSBNQVNDT1RBIiwiRURJVEFSIElORk9STUFDSU9OIERFIExBIE1BU0NPVEEiLCJFRElUQVIgVFJBVEFNSUVOVE9TIERFIExBIE1BU0NPVEEiLCJQVUJMSUNBUiBQUkVHVU5UQSJdLCJpc3MiOiJ1Y2IiLCJyZWZyZXNoIjpmYWxzZSwiZXhwIjoxNjcxNDg3NjQ4LCJpYXQiOjE2Njg0ODc2NDh9.ogfX8EtIlHACDTip3oEGW0eiYPKXcz8FMQ3f3SnhJBA

### Get veterinarian's answers by token
GET http://localhost:7777/v1/api/veterinarian/answers
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqdWFuMTIzIiwicm9sZXMiOlsiRURJVEFSIElORk9STUFDSU9OIERFIFZFVEVSSU5BUklPIiwiRURJVEFSIElORk9STUFDSU9OIERFIENMSU5JQ0EgVkVURVJJTkFSSUEiLCJQVUJMSUNBUiBSRVNQVUVTVEEiLCJFRElUQVIgUkVTUFVFU1RBIl0sImlzcyI6InVjYiIsInJlZnJlc2giOmZhbHNlLCJleHAiOjE2NzE0ODgwNzUsImlhdCI6MTY2ODQ4ODA3NX0.b3Ob-b8Rw6zORCuN24yxt4HCCyHrXZAdgCuRuYCEvmE

